version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${APP_SERVICE_MYSQL_DATABASE}
      - APP_SERVICE_MYSQL_URL=mysqldb
      - APP_SERVICE_MYSQL_PORT=3306
      - APP_SERVICE_MYSQL_DATABASE=${APP_SERVICE_MYSQL_DATABASE}
      - APP_SERVICE_MYSQL_USERNAME=${APP_SERVICE_MYSQL_USERNAME}
      - APP_SERVICE_MYSQL_PASSWORD=${APP_SERVICE_MYSQL_PASSWORD}
    networks:
      - springboot-mysql-network
    restart: always
  mysqldb:
    image: mysql:9.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${APP_SERVICE_MYSQL_DATABASE}
      - MYSQL_USER=${APP_SERVICE_MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${APP_SERVICE_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${APP_SERVICE_MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network