application:
  version: @appVersion@

spring:
  data:
    jpa:
      repositories:
        enabled: true
  application:
    name: ${APP_SERVICE_NAME:appointment_scheduler_rest_service}

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 50
    open-in-view: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${APP_SERVICE_MYSQL_URL}:${APP_SERVICE_MYSQL_PORT}/${APP_SERVICE_MYSQL_DATABASE:client_events_db}
    username: ${APP_SERVICE_MYSQL_USERNAME}
    password: ${APP_SERVICE_MYSQL_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 1800000

  flyway:
    locations: classpath:/db/mysql/migration
    url: jdbc:mysql://${APP_SERVICE_MYSQL_URL}:${APP_SERVICE_MYSQL_PORT}/${APP_SERVICE_MYSQL_DATABASE:client_events_db}?createDatabaseIfNotExist=true
    user: ${APP_SERVICE_MYSQL_USERNAME}
    password: ${APP_SERVICE_MYSQL_PASSWORD}
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    root: ${APP_SERVICE_ROOT_LOG_LEVEL:INFO}
    org.springframework: ${APP_SERVICE_SPRING_LOG_LEVEL:INFO}

server:
  port: ${PORT:8080}

  error:
    #
    # 1. with an always value;
    # includes the stacktrace in both the HTML and the JSON default response
    #
    include-stacktrace: always
    #
    # 2. Spring Boot hides the message field in the response to avoid leaking sensitive information;
    # we can use this property with an always value to enable it
    #
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include:
          - health

springdoc:
  swagger-ui:
    path: /api/documentation