spring:
  application:
    name: ${APP_SERVICE_NAME:appointment_scheduler_rest_service}

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    root: ${APP_SERVICE_ROOT_LOG_LEVEL:INFO}
    org.springframework: ${APP_SERVICE_SPRING_LOG_LEVEL:INFO}

server:
  port: ${APP_SERVICE_PORT:8080}

  error:
    #
    # 1. with an always value;
    # includes the stacktrace in both the HTML and the JSON default response
    #
    include-stacktrace: always
    #
    # 2. Spring Boot hides the message field in the response to avoid leaking sensitive information;
    # we can use this property with an always value to enable it
    #
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include:
          - health

springdoc:
  swagger-ui:
    path: /api/documentation